# Generated by Django 5.2.3 on 2025-06-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveClient",
            fields=[
                ("client_id", models.IntegerField(primary_key=True, serialize=False)),
                ("client_group", models.TextField()),
                ("client_subgroup", models.TextField()),
                ("state_code", models.TextField()),
                ("area", models.TextField()),
            ],
            options={
                "db_table": "analytics.active_clients_view",
                "managed": False,
            },
        ),
    ]
