# Generated by Django 5.2.3 on 2025-06-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.IntegerField(primary_key=True, serialize=False)),
                ("client_name", models.TextField()),
                ("gender", models.TextField()),
                ("marital_status", models.TextField()),
                ("age_band", models.TextField()),
                ("case_managers", models.TextField()),
                ("client_group", models.TextField()),
                ("client_subgroup", models.TextField()),
                ("hcp_level_name", models.TextField()),
                ("active_flag", models.TextField()),
                ("state_code", models.TextField()),
                ("area", models.TextField()),
            ],
            options={
                "db_table": "clients",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="ActiveClient",
        ),
    ]
